# Exercise 2.A Fundamentals of pandas

In [6]:
import numpy as np
import pandas as pd

## Series

In [7]:
aa = [1, 2, 3, 4]
ab = (5, 6, 7, 8)
ac = {9, 10, 11, 12}
ad = {'first': 13, 'second': 14, 'third': 15, 'fourth': 16}

ser1 = pd.Series(aa)
ser2 = pd.Series(ab)
ser3 = pd.Series(list(ac))
ser4 = pd.Series(ad)
print("ser1:\n", ser1, "\nser2:\n", ser2, "\nser3:\n", ser3, "\nser4:\n", ser4)

ser1:
 0    1
1    2
2    3
3    4
dtype: int64
ser2:
 0    5
1    6
2    7
3    8
dtype: int64
ser3:
 0     9
1    10
2    11
3    12
dtype: int64
ser4:
 first     13
second    14
third     15
fourth    16
dtype: int64

## DataFrames from Series

In [9]:
df1 = pd.DataFrame(ser1, columns=['col1'])
df1

df1.insert(1, 'col2', ser2)
df1.insert(2, 'col3', ser3)
df1

df1['col4'] = ser4
df1

   col1  col2  col3  col4
0     1     5     9   NaN
1     2     6    10   NaN
2     3     7    11   NaN
3     4     8    12   NaN

In [10]:
df1.loc[4] = [5, 9, 12, 0]
df1

   col1  col2  col3  col4
0     1     5     9   NaN
1     2     6    10   NaN
2     3     7    11   NaN
3     4     8    12   NaN
4     5     9    12   0.0

In [11]:
# Using info(), we can determine the number of rows and columns, the data types, 
# and whether there are any missing (null) values in the dataset.

In [12]:
# df2.describe()
#The describe() method provides useful statistical insights like mean, min/max, 
# and standard deviation for numeric columns. Summarizing reference ID columns is likely not useful.

In [13]:
# df3 = pd.read_csv('northwind_example.csv')
# df3.describe()

In [14]:
## Coding a DataFrame

In [15]:
test_data = {
    'ID': [1, 2, 3, 4, 5, 6, 7, 8],
    'Name': ['Alicia', 'Bob', 'Charlie', 'Dominic', 'Eve', 'Frank', 'Grace', 'Heidi'],
    'Age': [25, np.nan, 22, 19, 31, 35, np.nan, 18],
    'City': ['NY', 'LA', 'Chicago', 'Houston', 'Phoenix', 'Boston', 'Austin', 'San Diego'],
    'Score': [85, 92, -1, 65, 78, np.nan, 55, 90]
}
df4 = pd.DataFrame(test_data)
df4

df4.to_csv('test_data.csv', index=False)