# Exercise 2.C Working with multiple DataFrames

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'West', 'North', 'South', 'East'],
    'Units Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
    'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]
}
df_sales = pd.DataFrame(data)

In [4]:
df_sales['Revenue'] = df_sales['Units Sold'] * df_sales['Price']

In [5]:
total_units = df_sales['Units Sold'].sum()
total_revenue = df_sales['Revenue'].sum()

In [6]:
avg_units = df_sales['Units Sold'].mean()
avg_revenue = df_sales['Revenue'].mean()

## Grouping Data

In [7]:
df_sales.groupby('Product')[['Units Sold', 'Revenue']].sum()
df_sales.groupby('Region')[['Units Sold', 'Revenue']].mean()
df_sales.groupby(['Product', 'Region'])[['Units Sold', 'Revenue']].sum()

                Units Sold  Revenue
Product Region
A       North           20     2000
        West             5      500
B       North           10     2000
        South           20     4000
C       East            35     5250
        West            15     2250

## Sorting and Ranking Data

In [8]:
df_sales = df_sales.sort_values(by='Units Sold', ascending=True)
df_sales = df_sales.sort_values(by='Revenue', ascending=False)
df_sales['Revenue_Rank'] = df_sales['Revenue'].rank(ascending=False)
df_sales

  Product Region  Units Sold  Price  Revenue  Revenue_Rank
1       B  South          15    200     3000           1.5
2       C   East          20    150     3000           1.5
5       C   West          15    150     2250           3.5
8       C   East          15    150     2250           3.5
4       B  North          10    200     2000           5.0
7       B  South           5    200     1000           7.0
0       A  North          10    100     1000           7.0
6       A  North          10    100     1000           7.0
3       A   West           5    100      500           9.0

## Merging DataFrames

In [9]:
product_data = {'Product': ['A', 'B', 'C'], 'Category': ['Electronics', 'Furniture', 'Appliances']}
df_products = pd.DataFrame(product_data)

In [10]:
df_merged = pd.merge(df_sales, df_products, on='Product')
df_merged

  Product Region  Units Sold  Price  Revenue  Revenue_Rank     Category
0       B  South          15    200     3000           1.5    Furniture
1       C   East          20    150     3000           1.5   Appliances
2       C   West          15    150     2250           3.5   Appliances
3       C   East          15    150     2250           3.5   Appliances
4       B  North          10    200     2000           5.0    Furniture
5       B  South           5    200     1000           7.0    Furniture
6       A  North          10    100     1000           7.0  Electronics
7       A  North          10    100     1000           7.0  Electronics
8       A   West           5    100      500           9.0  Electronics

In [11]:
df_merged.groupby('Category')['Revenue'].sum()

Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64